name: vault_01
description: A secure password manager application.
publish_to: 'none'
version: 1.0.0+1

environment:
  # This was the issue. We updated it to support Dart 3.
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

  # Storage & Utilities
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.1
  path_provider: ^2.1.5
  path: ^1.9.1

  # Codegen / Native Bridge
  flutter_rust_bridge: ^2.11.1

  # Icons
  cupertino_icons: ^1.0.2

  # Authentication
  google_sign_in: ^6.1.0
  # ... existing dependencies
  local_auth: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true