[package]
name = "rust_lib_vault_01"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]

flutter_rust_bridge = "=2.11.1"

# The Database Engine
# feature "bundled-sqlcipher" = Downloads & statically links SQLCipher (Encryption supported)
# We avoid "bundled" because that gives us plain text SQLite.
rusqlite = { version = "0.31.0", features = ["bundled-sqlcipher"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
